[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "LethalRichPresence"
description = "Discord Rich Presence support in-game."
websiteUrl = "https://github.com/AndreyMrovol/LethalRichPresence"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-MrovLib = "0.2.7"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../LethalRichPresence/dist"

[[build.copy]]
source = "../LethalRichPresence/bin/Release/netstandard2.1/LethalRichPresence.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]